### ISSUE TITLE
I can not use onAction="#foo" in perspective- and component- FXML, BUG or FEATURE?

### ISSUE THREAD

**Issue by Mehonidas** [JacpFX/JacpFX#35] opened 2015-06-16 08:27 UTC
Hi@ all,
if i tried to load a FXML structure in a perspective or a component, i got this error. 
``` 
java.util.MissingResourceException: fxml file not found --  place in resource folder and reference    like this: viewLocation = "/myUIFile.fxml"
```
The FXML file include parts like this: ```<Button onAction="#save" text="Save" /> ```
If i deleted this part it works!

Is this a bug, a feature or what i am doing wrong?

Thank you for response!

Greetings Meho

**Comment by amoAHCP** [comment] 2015-06-17 11:59
Hi, this is simply a bug which gives you the incorrect stacktrace. This will be fixed in JacpFX2.1... if you can't find the cause I can show you where to set the breakpoint to get the correct cause.


Andy

**Comment by Mehonidas** [comment] 2015-06-18 10:29
Hi Andy,
i work around and set onAction() in the JavaFX code and not in FXML.
Thank you for the response. So i dont search for a mistake at the wrong position!

Bye Meho

**Closed** 2015-06-23 14:53 UTC
